name: memory_journey
description: "A Flutter Memory Journey App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background_music.mp3
    - assets/download_1.png
    - assets/download_2.png
    - assets/download_3.png
    - assets/download_4.png
    - assets/download_5.png
    - assets/character_1.png
    - assets/character_2.png
    - assets/character_3.png
    - assets/character_4.png
    - assets/character_5.png
